services:
  - type: web
    name: precificacion-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    env: static
    rootDir: server
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_SHEET_ID_USUARIOS
        sync: false
      - key: GOOGLE_SHEET_ID_PRODUCTOS
        sync: false
      - key: GOOGLE_SHEET_ID_MATERIAS
        sync: false
      - key: GOOGLE_SHEET_ID_CONTABILIDAD
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_API_URL
        value: https://api-m.paypal.com
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
